# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|                # Bắt đầu khai báo máy ảo
    config.vm.box = 'centos/7'                    # Sử dụng Box centos/7 tạo máy ảo
  
    
    config.vm.network "private_network", ip: "192.168.99.99"   # Lập IP cho máy ảo
    config.vm.hostname = "master.xtl"             # Đặt hostname cho máy ảo

    config.vm.provider "virtualbox2023" do |vb|       # Máy ảo dùng nền tảng virtualbox, với các cấu hình bổ sung thêm cho provider
       vb.name = "forumhust"                      # đặt tên máy ảo tạo ra
       vb.cpus = 2                                # cấp 2 nhân CPU
       vb.memory = "10240"                         # cấu hình dùng 10GB bộ nhớ
    end                                           # hết cấu hình provider

    config.vm.provision "shell", path: "install.sh"
  end 